### ISSUE TITLE
Auth abstract controller fails when extends from the regular controller

### ISSUE THREAD

**Issue by chrissmejia** [chrissmejia/JSloth#2]
AuthController (\source\auth\abstract\controller) is mostly a copy of the system controller (\source\core\abstract), but when you try to extend it to add the auth middleware and test the tokens it fails:
```
- auth routes not found
Error: Route.get() requires callback functions but got a [object Undefined]
    at Route.(anonymous function) [as get] (C:\Users\chrid\Documents\sites\JSloth\node_modules\express\lib\router\route.js:202:15)
    at Function.proto.(anonymous function) [as get] (C:\Users\chrid\Documents\sites\JSloth\node_modules\express\lib\router\index.js:510:19)
    at CoreEndPoint.routes (C:\Users\chrid\Documents\sites\JSloth\source\auth\endpoints\coreEndpoint.ts:150:21)
    at CoreEndPoint.Controller (C:\Users\chrid\Documents\sites\JSloth\source\core\abstract\controller.ts:44:14)
    at CoreEndPoint.Controller [as constructor] (C:\Users\chrid\Documents\sites\JSloth\source\auth\abstract\controller.ts:47:9)
    at new CoreEndPoint (C:\Users\chrid\Documents\sites\JSloth\source\auth\endpoints\coreEndpoint.ts:48:9)
    at Routes.load (C:\Users\chrid\Documents\sites\JSloth\source\core\abstract\routes.ts:54:24)
    at Routes.routes (C:\Users\chrid\Documents\sites\JSloth\source\auth\api.ts:41:35)
    at Routes (C:\Users\chrid\Documents\sites\JSloth\source\core\abstract\routes.ts:45:14)
    at new Routes (C:\Users\chrid\Documents\sites\JSloth\source\auth\api.ts:12:23)
- health routes installed
```
If you duplicate the code instead of extend it, like it is right now, it works.
If you extends but don't use the middleware it works.

Any ideas?

**Comment by chrissmejia** [comment]
Fixed :)
